---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# python-dynamic-version-action
name: "🐍 Check Python Project for Dynamic Versioning"
description: "Checks if dynamic versioning is enabled in pyproject.toml"

inputs:
  # Optional
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""
outputs:
  DYNAMIC_VERSION:
    description: "Set true when dynamic versioning configured"
    value: ${{ steps.parse.outputs.dynamic_version }}

runs:
  using: "composite"
  steps:
    - name: "Check for required pyproject.toml file"
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      with:
        path: "${{ inputs.path_prefix }}pyproject.toml"

    - id: parse
      name: "Check for dynamic project versioning"
      shell: bash
      run: |
        # Check for dynamic project versioning
        if (grep -q 'dynamic = \["version"\]' \
          ${{ inputs.path_prefix }}pyproject.toml); then
          echo "Dynamic versioning configured ✅"
          echo "dynamic_version=true" >> "$GITHUB_ENV"
          echo "dynamic_version=true" >> "$GITHUB_OUTPUT"
        else
          echo "Dynamic versioning NOT configured"
          echo "dynamic_version=false" >> "$GITHUB_ENV"
          echo "dynamic_version=false" >> "$GITHUB_OUTPUT"
        fi
