---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-dynamic-version-action
name: '🐍 Python Project Dynamic Versioning'
description: 'Checks dynamic versioning setup in the pyproject.toml file'

inputs:
  # Optional
  path_prefix:
    description: 'Directory location containing project code'
    type: string
    required: false
    default: '.'

outputs:
  dynamic_version:
    description: 'Set true when dynamic versioning configured'
    value: "${{ steps.parse.outputs.dynamic_version }}"

runs:
  using: 'composite'
  steps:
    - name: 'Verify action/environment'
      shell: bash
      run: |
        # Verify action/environment
        if [ ! -d "${{ inputs.path_prefix }}" ]; then
          echo "Error: invalid path/prefix to project directory ❌"; exit 1
        fi

    - name: 'Check for required pyproject.toml file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/path-check-action@594fa4a73651e3e869a4829397e878932f7db32c # v0.1.4
      with:
        path: "${{ inputs.path_prefix }}/pyproject.toml"

    - id: parse
      name: 'Check for dynamic project versioning'
      shell: bash
      run: |
        # Check for dynamic project versioning
        if (grep -q 'dynamic = \["version"\]' \
          ${{ inputs.path_prefix }}/pyproject.toml); then
          echo 'Dynamic versioning configured ✅'
          echo "dynamic_version=true" >> "$GITHUB_ENV"
          echo "dynamic_version=true" >> "$GITHUB_OUTPUT"
        else
          echo 'Dynamic versioning is NOT configured 💬'
          echo "dynamic_version=false" >> "$GITHUB_ENV"
          echo "dynamic_version=false" >> "$GITHUB_OUTPUT"
        fi
